---

parser: "@babel/eslint-parser"
parserOptions:
    requireConfigFile: false

plugins:
  - react
  - functional

extends:
  - airbnb
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"

env:
  browser: true
  node: true

rules:
  import/extensions: 0
  # TODO: cause an error
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  "linebreak-style": 0
  react/jsx-wrap-multilines: 0
  react-hooks/exhaustive-deps: 0

overrides:
  - files:
      - "__test__/*/*.js"
      - "__test__/*/*.jsx"
      - "__mocks__/*/*.js"
      - "__mocks__/*.js"
      - "src/components/__mocks__/*.jsx"
      - "src/hooks/__mocks__/*.js"
    rules:
      no-undef: 0
      import/no-extraneous-dependencies: 0
      import/prefer-default-export: 0
      import/named: 0
      functional/no-let: 0
      react-hooks/rules-of-hooks: 0
  - files:
      - "src/store/reducers/*.js"
      - "src/utils/modifyBuilder.js"
      - "src/http/index.js"
    rules:
      no-param-reassign: 0
  - files:
      - "webpack/*"
    rules:
      no-unused-vars: 0
  - files:
      - "src/hooks/useUser.js"
      - "src/hooks/useDevice.js"
    rules:
      functional/no-this-expression: 0
  - files:
    - "index.jsx"
    rules:
      no-undef: 0