name: test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

env:
  REACT_APP_HOST: http://localhost:5000

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: npm i
      - name: Run unit tests
        run: npm run test:unit
      - name: Run e2e tests
        run: npm run test